######################################################################
# Evaluation settings
######################################################################
eval_keys: ["in_goal_cells_changed", "in_goal_mean_diff", "execution_steps"]
eval_episodes: 100 # [episodes]

######################################################################
# File handling
######################################################################
save_eval_folder: "evaluation"